import "./globals.css";
import { Inter } from "next/font/google";
import { AOSInit } from "@/utils/aos";
import ScrollToTop from "@/utils/ScrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "گرین کافی",
  icons: {
    icon: "https://creazilla-store.fra1.digitaloceanspaces.com/cliparts/36190/coffee-logo-clipart-md.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className={inter.className}>
        <AOSInit />
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
